Use version prefix for assembly and file versions
Fixes `error CS7034: The specified version string '0.1.0-alpha.2' does not conform to the required format - major[.minor[.build[.revision]]]`